pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo '¡Hola Mundo! El pipeline está funcionando desde el repo limpio.'
            }
        }
    }
}